### PR TITLE
Updated Rust MS Windows FAQ

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by danintel — CHANGES_REQUESTED** [review]
Thanks for taking time to file a PR with the doc fixes!

Your commit message needs a DCO line in the last line of your commit message, with your github account name and email address.
For you, I think it would be:

`Signed-off-by: colincmcc <hello@colinmac.me>`

(change your.email.here@somewhere.com). This is a legal requirement by The Linux Foundation and Hyperledger.
See https://sawtooth.hyperledger.org/docs/core/releases/latest/community/contributing.html

**Comment by ghost** [comment]
Sorry about that typed -S instead of -s . Fixed!  I can submit a new pull request if you'd like, but the last commit has the signature

**Comment by danintel** [comment]
Thanks. Please squash all the commits into 1 commit with the DCO. There's a check for sign-offs that would otherwise fail. You can force push the squashed commits or submit a new PR--either way is OK with me.

**Comment by ghost** [comment]
done!

**Pull request merged**
